"""All models created

Revision ID: 5a71a4225ff6
Revises: 
Create Date: 2025-06-05 16:30:40.648843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a71a4225ff6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('ACTION', 'THRILLER', 'DRAMA', 'COMEDY', 'HORROR', 'WESTERN', name='genreenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    op.create_table('userindb',
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String, nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sa.String, nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ratingdb',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('stars', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='stars'), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userindb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('session_time', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokenrefresh',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userindb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenrefresh_token'), 'tokenrefresh', ['token'], unique=True)
    op.create_table('booking',
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', 'PAYMENT_PENDING', 'EXPIRED', 'CHECKED_IN', 'NO_SHOW', 'REFUNDED', name='bookingstatus'), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userindb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seat_number', name='uix_session_seat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat')
    op.drop_table('booking')
    op.drop_index(op.f('ix_tokenrefresh_token'), table_name='tokenrefresh')
    op.drop_table('tokenrefresh')
    op.drop_table('session')
    op.drop_table('ratingdb')
    op.drop_table('userindb')
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
