"""Added trailer_url to movies

Revision ID: 685db076633a
Revises: 5a71a4225ff6
Create Date: 2025-06-06 21:07:12.663266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685db076633a'
down_revision: Union[str, None] = '5a71a4225ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('trailer_url', sa.String, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'trailer_url')
    # ### end Alembic commands ###
