"""New seat ids field in booking talbe model

Revision ID: e301222913f0
Revises: 685db076633a
Create Date: 2025-06-09 15:24:11.905306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e301222913f0'
down_revision: Union[str, None] = '685db076633a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('seat_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'seat_ids')
    # ### end Alembic commands ###
