"""Added director, language and country fields to movie

Revision ID: e56ea3148255
Revises: e301222913f0
Create Date: 2025-06-09 17:53:21.159418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56ea3148255'
down_revision: Union[str, None] = 'e301222913f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('director', sa.String, nullable=True))
    op.add_column('movie', sa.Column('language', sa.String, nullable=True))
    op.add_column('movie', sa.Column('country', sa.String, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'country')
    op.drop_column('movie', 'language')
    op.drop_column('movie', 'director')
    # ### end Alembic commands ###
